package pin.observer;
/**
 * Implementation of the PasswordObserver interface.
 * This class provides a way to notify when a password is generated by printing it to the standard output.
 */
public class PasswordNotifier implements PasswordObserver {
    /**
     * Called when a password is generated.
     * Prints the generated password to the standard output.
     *
     * @param password The generated password.
     */
    @Override
    public void onPasswordGenerated(String password) {
        System.out.println("Password has been generated: " + password);
    }
}
